FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY personal-website.Server/*.csproj ./personal-website.Server
RUN dotnet restore personal-website.Server/personal-website.Server.csproj

COPY . .
WORKDIR /src/personal-website.Server
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /app ./

ENV ASPNETCore_URLS=https://+:${PORT}

EXPOSE 10000
ENTRYPOINT [ "dotnet", "personal-website.Server.dll" ]