// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using personal_website.Server.Data;

#nullable disable

namespace personal_website.Server.Migrations
{
    [DbContext(typeof(personal_websiteServerContext))]
    [Migration("20250227222729_AddedImageId")]
    partial class AddedImageId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("personal_website.Server.Models.Blogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "I love cats",
                            CategoryId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cats",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Visibility = 0
                        },
                        new
                        {
                            Id = 2,
                            Body = "I love Taco",
                            CategoryId = 7,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Taco",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Visibility = 0
                        });
                });

            modelBuilder.Entity("personal_website.Server.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Pets"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Cats",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Dogs",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Technology"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Software",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Website",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Foods"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Arts"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Fitness"
                        });
                });

            modelBuilder.Entity("personal_website.Server.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedbackComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedbackName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NeededResponse")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Feedback");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test@test.com",
                            FeedbackComment = "I love this website",
                            FeedbackName = "Website",
                            NeededResponse = false
                        },
                        new
                        {
                            Id = 2,
                            Email = "meow@meow.com",
                            FeedbackComment = "This website has security vulnerability",
                            FeedbackName = "Security Vulnerability",
                            NeededResponse = true
                        },
                        new
                        {
                            Id = 3,
                            Email = "Real@fake.com",
                            FeedbackComment = "This previous post is a lie",
                            FeedbackName = "Fake News",
                            NeededResponse = false
                        });
                });

            modelBuilder.Entity("personal_website.Server.Models.PortfolioItemImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PortfolioItemImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pic of cat",
                            FileSize = 100000,
                            Name = "Cat"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pic of taco",
                            FileSize = 1000,
                            Name = "Taco"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pic of dog",
                            FileSize = 100000000,
                            Name = "dog"
                        });
                });

            modelBuilder.Entity("personal_website.Server.Models.PortfolioItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Links")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImageId");

                    b.ToTable("PortfolioItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cat pic",
                            ImageId = 1,
                            Links = "github.com",
                            Title = "Cat",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 7,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Taco pic",
                            ImageId = 2,
                            Links = "meow.com",
                            Title = "Taco",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = "0.0.3"
                        });
                });

            modelBuilder.Entity("personal_website.Server.Models.Blogs", b =>
                {
                    b.HasOne("personal_website.Server.Models.Categories", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("personal_website.Server.Models.PortfolioItems", b =>
                {
                    b.HasOne("personal_website.Server.Models.Categories", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("personal_website.Server.Models.PortfolioItemImages", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Image");
                });
#pragma warning restore 612, 618
        }
    }
}
